//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaAspNetMVC.BaseDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detdocumento
    {
        public int numdocdet { get; set; }
        public Nullable<int> numdoc { get; set; }
        public Nullable<int> linea { get; set; }
        public string nombreprod { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual cabdocumento cabdocumento { get; set; }
    }
}
